### ISSUE TITLE
404 Error on new inventory element POST API 

### ISSUE THREAD

**Issue by tiffany-slac** [eed-web-application/core-inventory-system#16]
When attempting to create an inventory element using the frontend interface, encountered a 404 Not Found error.

Endpoint: http://localhost:3000/api/v1/inventory/domain/657255739020e27c45093338/element

Payload: {
    "name": "LAC0941",
    "classId": "Item",
    "parentId": "na",
    "dsecription": "description",
    "tags": [],
    "attributes": []
}

Verified the frontend code and the data being sent to the endpoint. All required fields are being included in the request payload. The x-vouch-idp-accesstoken is extracted correctly and included in the request header. Checked backend logs and didn't find specific errors related to this endpoint.

**Comment by bisegni** [comment]
i see a problem here "parentId": "na", parent id or is null or is an id of an already store element so the 404 error is got because the backend did't find the parentID element. Generally each error came with a errorMessage and errorDomain, check in the json serialization that you got as response





[10:48 AM](https://slac.slack.com/archives/D06639BUCSX/p1702061335637519)
you should get on the serailization the rrorMessage and errorDOmain filed
[10:49 AM](https://slac.slack.com/archives/D06639BUCSX/p1702061352851409)
the 404 is got because the parentId is not found

**Comment by bisegni** [comment]
can you past all the response buffer?
